export const routes = {
  auth: {
    login: "/login",
    onboarding: "/onboarding",
    register: "/login",
    logout: "/login",
  },
  dashboard: "/dashboard",
  transactions: "/riwayat",
  catatManual: "/catat/manual",
  catatSuara: "/catat/suara",
  catatNota: "/catat/nota",
  reviewDraft: (draftId: string) => `/catat/review/${draftId}`,
  riwayat: "/riwayat",
  laporan: "/laporan",
  ekraf: "/ekraf",
  studio: "/studio",
  hki: "/hki",
  assistant: "/asisten",
  settings: "/pengaturan",
  settingsUsaha: "/pengaturan/usaha",
  settingsProfil: "/pengaturan/profil",
  settingsPrivasi: "/pengaturan/privasi",
  settingsData: "/pengaturan/data",
  gamifikasi: "/gamifikasi",
};